- name: Install Tools
  apt: name={{ item }} state=latest update_cache=true
  with_items:
    - build-essential
    - tmux
    - vim
    - htop
    - git-core
    - wget
    - zlib1g-dev
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libxml2-dev
    - libxslt1-dev
    - libffi-dev
    - curl
    - libcurl3
    - libcurl3-gnutls
    - libcurl4-openssl-dev
    - nodejs
